# Generated by Django 3.1.7 on 2021-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(max_length=11)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('deliveryAddress', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('storeId', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=255)),
                ('storeAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='webuser',
            fields=[
                ('userID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(max_length=11)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('deliveryAddress', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('paymentID', models.IntegerField(max_length=10)),
            ],
        ),
    ]
