# Generated by Django 3.1.7 on 2021-05-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emailAddress',
            field=models.EmailField(max_length=255),
        ),
    ]
