# Generated by Django 3.1.7 on 2021-04-14 23:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groceryorder',
            fields=[
                ('orderID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('deliveryDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructions', models.TextField()),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=65)),
                ('deliveryFee', models.DecimalField(decimal_places=2, max_digits=65)),
                ('tip', models.DecimalField(decimal_places=2, max_digits=65)),
                ('total', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('image', models.URLField()),
                ('brandName', models.CharField(max_length=255)),
                ('tagID', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('storeId', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=255)),
                ('storeAddress', models.CharField(max_length=255)),
            ],
        ),

        migrations.CreateModel(
            name='webuser',
            fields=[
                ('userID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(max_length=11)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('deliveryAddress', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('paymentID', models.IntegerField(max_length=10)),
            ],
        ),

        migrations.CreateModel(
            name='driver',
            fields=[
                ('webuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lastshop.webuser')),
                ('averageRating', models.DecimalField(decimal_places=1, max_digits=65, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('bank', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('mailAddress', models.CharField(max_length=255)),
            ],
            bases=('lastshop.webuser',),
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=255)),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.item')),
            ],
        ),
        migrations.CreateModel(
            name='suborder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField(max_length=10)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=65)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=65)),
                ('total', models.DecimalField(decimal_places=2, max_digits=65)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.groceryorder')),
            ],
        ),
        migrations.CreateModel(
            name='paymentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=255)),
                ('cardNumber', models.BigIntegerField(max_length=16)),
                ('pinNumber', models.IntegerField(max_length=4)),
                ('expirationDate', models.DateField()),
                ('billAddress', models.CharField(max_length=255)),
                ('default', models.BooleanField()),
                ('paymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.webuser')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='storeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.store'),
        ),
        migrations.AddField(
            model_name='groceryorder',
            name='deliveryAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceryDeliveryAddress', to='lastshop.webuser'),
        ),
        migrations.AddField(
            model_name='groceryorder',
            name='paymentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceryPaymentID', to='lastshop.webuser'),
        ),
        migrations.AddField(
            model_name='groceryorder',
            name='phoneNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceryPhoneNumber', to='lastshop.webuser'),
        ),
        migrations.AddField(
            model_name='groceryorder',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceryUserName', to='lastshop.webuser'),
        ),
        migrations.CreateModel(
            name='grocerylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.item')),
                ('listID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.suborder')),
            ],
        ),
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.item')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.webuser')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.item')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastshop.webuser')),
            ],
        ),
    ]