# Generated by Django 3.1.7 on 2021-04-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='webuser_ptr',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='listID',
        ),
        migrations.RemoveField(
            model_name='groceryorder',
            name='deliveryAddress',
        ),
        migrations.RemoveField(
            model_name='groceryorder',
            name='paymentID',
        ),
        migrations.RemoveField(
            model_name='groceryorder',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='groceryorder',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='storeID',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='paymentID',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagID',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='driver',
        ),
        migrations.DeleteModel(
            name='favorite',
        ),
        migrations.DeleteModel(
            name='grocerylist',
        ),
        migrations.DeleteModel(
            name='groceryorder',
        ),
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='paymentinfo',
        ),
        migrations.DeleteModel(
            name='store',
        ),
        migrations.DeleteModel(
            name='suborder',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.DeleteModel(
            name='webuser',
        ),
    ]
