# Generated by Django 3.1.7 on 2021-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastshop', '0004_remove_groceryorder_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
